---
# ====================================================
# Deploy Respect Us Application to K3s Cluster
# ====================================================

# -------------------------
# Pre-flight checks (runs on all hosts)
# -------------------------
- name: Pre-flight validation
  hosts: all
  become: yes
  vars:
    respect_us_path: /opt/respect-us
    backend_image: "imoresdev/respect-us:backend"
    frontend_image: "imoresdev/respect-us:frontend"
    registry_user: "{{ lookup('env','DOCKER_USER') }}"
    registry_password: "{{ lookup('env','DOCKER_PASS') }}"
    k3s_kubeconfig: /etc/rancher/k3s/k3s.yaml
    namespace: respect-us
    domain_name: respect-us.local
    backend_replicas: 2
    frontend_replicas: 2
    resource_requests:
      memory: "256Mi"
      cpu: "250m"
    resource_limits:
      memory: "512Mi"
      cpu: "500m"

  pre_tasks:
    - name: Validate Docker registry credentials
      fail:
        msg: "DOCKER_USER and DOCKER_PASS must be set for Docker registry login."
      when: registry_user == "" or registry_password == ""
      tags: [always]

    - name: Check for respect-us.zip on controller
      ansible.builtin.stat:
        path: "../respect-us.zip"
      register: zip_file_check
      delegate_to: localhost
      tags: [always]

    - name: Fail if respect-us.zip is missing
      fail:
        msg: "respect-us.zip not found at ../respect-us.zip"
      when: not zip_file_check.stat.exists
      tags: [always]


# -------------------------
# K3s master setup
# -------------------------
- name: K3s master setup
  hosts: k3s_master
  become: yes
  tasks:
    - name: Ensure K3s installed on master
      shell: curl -sfL https://get.k3s.io | sh
      args:
        creates: /usr/local/bin/k3s

    - name: Fetch K3S token
      shell: cat /var/lib/rancher/k3s/server/node-token
      register: k3s_token

    - name: Set master token fact
      set_fact:
        master_token: "{{ k3s_token.stdout }}"


# -------------------------
# K3s worker setup
# -------------------------
- name: Join workers to K3s cluster
  hosts: k3s_worker
  become: yes
  tasks:
    - name: Join worker node to K3s cluster
      shell: |
        K3S_URL="https://{{ hostvars['k3s_master'].ansible_default_ipv4.address }}:6443"
        K3S_TOKEN="{{ hostvars['k3s_master'].master_token }}"
        curl -sfL https://get.k3s.io | K3S_URL=$K3S_URL K3S_TOKEN=$K3S_TOKEN sh -
      args:
        creates: /usr/local/bin/k3s


# -------------------------
# Setup system packages and directories
# -------------------------
- name: Setup system packages and directories
  hosts: all
  become: yes
  tasks:
    - name: Install prerequisites
      apt:
        name:
          - unzip
          - python3-pip
        state: present
        update_cache: yes

    - name: Install Kubernetes Python client
      pip:
        name:
          - kubernetes
          - pyyaml
        state: present

    - name: Create respect-us directory structure
      file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
        owner: root
        group: root
      loop:
        - "{{ respect_us_path }}"
        - "{{ respect_us_path }}/logs"
        - "{{ respect_us_path }}/configs"
        - "{{ respect_us_path }}/backend"
        - "{{ respect_us_path }}/frontend"


# -------------------------
# Deploy application code
# -------------------------
- name: Deploy application code from ZIP
  hosts: all
  become: yes
  tasks:
    - name: Remove old backend/frontend
      file:
        path: "{{ respect_us_path }}/{{ item }}"
        state: absent
      loop:
        - backend
        - frontend

    - name: Extract respect-us.zip
      ansible.builtin.unarchive:
        src: ../respect-us.zip
        dest: "{{ respect_us_path }}"
        remote_src: false
        mode: '0755'

    - name: Verify backend/frontend directories exist
      stat:
        path: "{{ respect_us_path }}/{{ item }}"
      loop:
        - backend
        - frontend
      register: dir_exists

    - name: Fail if backend/frontend missing
      fail:
        msg: "Extraction failed: Missing {{ item.item }}"
      loop: "{{ dir_exists.results }}"
      when: not item.stat.exists

    - name: Set permissions on extracted files
      file:
        path: "{{ respect_us_path }}"
        recurse: yes
        mode: 'u=rwX,g=rX,o=rX'
        owner: root
        group: root


# -------------------------
# Install and configure Docker
# -------------------------
- name: Install and configure Docker
  hosts: all
  become: yes
  tasks:
    - name: Install prerequisites
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
          - software-properties-common
        state: present
        update_cache: yes

    - name: Add Docker's GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
        keyring: /usr/share/keyrings/docker-archive-keyring.gpg

    - name: Add Docker repository
      apt_repository:
        repo: "deb [arch={{ ansible_architecture | replace('x86_64','amd64') }} signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present
        update_cache: yes

    - name: Install Docker packages
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present
        update_cache: yes

    - name: Configure Docker daemon
      copy:
        dest: /etc/docker/daemon.json
        content: |
          {
            "log-driver": "json-file",
            "log-opts": { "max-size": "10m", "max-file": "3" },
            "storage-driver": "overlay2",
            "live-restore": true,
            "userland-proxy": false
          }
      notify:
        - restart docker

    - name: Start and enable Docker
      systemd:
        name: docker
        state: started
        enabled: yes


# -------------------------
# Build and push Docker images
# -------------------------
- name: Build and push Docker images
  hosts: all
  become: yes
  tasks:
    - name: Docker login
      community.docker.docker_login:
        username: "{{ registry_user }}"
        password: "{{ registry_password }}"
        reauthorize: yes
      no_log: true

    - name: Build backend image
      community.docker.docker_image:
        name: "{{ backend_image }}"
        source: build
        build:
          path: "{{ respect_us_path }}/backend"
          pull: yes
          nocache: yes
        tag: "{{ backend_image.split(':')[1] }}"

    - name: Push backend image
      community.docker.docker_image:
        name: "{{ backend_image }}"
        push: true
        source: local

    - name: Build frontend image
      command: docker build -t "{{ frontend_image }}" .
      args:
        chdir: "{{ respect_us_path }}/frontend"
      async: 3600
      poll: 30

    - name: Push frontend image
      community.docker.docker_image:
        name: "{{ frontend_image }}"
        push: true
        source: local


# -------------------------
# Deploy Kubernetes resources
# -------------------------
- name: Deploy Kubernetes resources
  hosts: all
  become: yes
  tasks:
    - name: Create namespace
      kubernetes.core.k8s:
        api_version: v1
        kind: Namespace
        name: "{{ namespace }}"
        state: present
        kubeconfig: "{{ k3s_kubeconfig }}"

    - name: Create Docker registry secret
      kubernetes.core.k8s:
        state: present
        kubeconfig: "{{ k3s_kubeconfig }}"
        definition:
          apiVersion: v1
          kind: Secret
          metadata:
            name: docker-registry-secret
            namespace: "{{ namespace }}"
          type: kubernetes.io/dockerconfigjson
          data:
            .dockerconfigjson: "{{ lookup('template','docker-config.json.j2') | b64encode }}"
      no_log: true

    - name: Deploy backend
      kubernetes.core.k8s:
        state: present
        kubeconfig: "{{ k3s_kubeconfig }}"
        definition:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: respect-us-backend
            namespace: "{{ namespace }}"
          spec:
            replicas: "{{ backend_replicas }}"
            selector:
              matchLabels:
                app: respect-us-backend
            template:
              metadata:
                labels:
                  app: respect-us-backend
              spec:
                containers:
                  - name: backend
                    image: "{{ backend_image }}"
                    ports:
                      - containerPort: 8000
                    resources:
                      requests:
                        memory: "{{ resource_requests.memory }}"
                        cpu: "{{ resource_requests.cpu }}"
                      limits:
                        memory: "{{ resource_limits.memory }}"
                        cpu: "{{ resource_limits.cpu }}"

    - name: Deploy frontend
      kubernetes.core.k8s:
        state: present
        kubeconfig: "{{ k3s_kubeconfig }}"
        definition:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: respect-us-frontend
            namespace: "{{ namespace }}"
          spec:
            replicas: "{{ frontend_replicas }}"
            selector:
              matchLabels:
                app: respect-us-frontend
            template:
              metadata:
                labels:
                  app: respect-us-frontend
              spec:
                containers:
                  - name: frontend
                    image: "{{ frontend_image }}"
                    ports:
                      - containerPort: 3000
                    resources:
                      requests:
                        memory: "{{ resource_requests.memory }}"
                        cpu: "{{ resource_requests.cpu }}"
                      limits:
                        memory: "{{ resource_limits.memory }}"
                        cpu: "{{ resource_limits.cpu }}"


# -------------------------
# Handlers
# -------------------------
- name: Handlers
  hosts: all
  become: yes
  tasks:
    - name: restart docker
      systemd:
        name: docker
        state: restarted
        daemon_reload: yes
