# -----------------------------
# K3s master
# -----------------------------
- hosts: k3s_master
  become: yes
  tasks:
    - name: Install k3s master
      shell: |
        curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--write-kubeconfig-mode 644" sh -

    - name: Fetch K3S token
      command: cat /var/lib/rancher/k3s/server/node-token
      register: k3s_token
      changed_when: false

    # Save token to a file so workers can read it
    - name: Write K3S token to file
      copy:
        content: "{{ k3s_token.stdout }}"
        dest: /tmp/k3s_token.txt
      run_once: true
      delegate_to: localhost

# -----------------------------
# K3s workers
# -----------------------------
- hosts: k3s_workers
  become: yes
  vars:
    master_ip: "{{ hostvars[groups['k3s_master'][0]]['ansible_host'] }}"
  tasks:
    - name: Read K3S token
      slurp:
        src: /tmp/k3s_token.txt
      register: token_file
      delegate_to: localhost
      run_once: true

    - name: Set token fact on workers
      set_fact:
        k3s_token: "{{ token_file.content | b64decode }}"

    - name: Join worker to k3s cluster
      shell: |
        curl -sfL https://get.k3s.io | K3S_URL=https://{{ master_ip }}:6443 K3S_TOKEN={{ k3s_token }} sh -
      args:
        creates: /usr/local/bin/k3s
