name: Deployment

on:
  push:
    branches:
      - main  # run when pushing to main

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      DOCKER_USER: ${{ secrets.DOCKER_USER }}
      DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
      HETZNER_TOKEN: ${{ secrets.HETZNER_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: latest

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -var="hcloud_token=${{ secrets.HETZNER_TOKEN }}" -out=tfplan

      - name: Terraform Apply
        run: terraform apply -input=false -auto-approve \
          -var="hcloud_token=${{ secrets.HETZNER_TOKEN }}" \
          -var="docker_user=${{ secrets.DOCKER_USER }}" \
          -var="docker_pass=${{ secrets.DOCKER_PASS }}"


      - name: Terraform Destroy on failure
        if: failure()   # runs only if any previous step fails
        run: terraform destroy -auto-approve -var="hcloud_token=${{ secrets.HETZNER_TOKEN }}"